### ISSUE TITLE
Does not seem to working when used in conjunction with swup preload plugin

### ISSUE THREAD

**Issue by kaspost** [swup/custom-payload-plugin#1]
**Describe your issue**:
I'm trying to send and parse JSON responses when a page is requested with the HTTP_X_REQUESTED_WITH: swup header set. The getDataFromHtml function works completely fine inside the generatePageObject function. However, this error is thrown when preloading pages:
```
Swup.modern.js:21 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at new m (Swup.modern.js:21:2193)
    at m.fromUrl (Swup.modern.js:21:2374)
    at E.getCacheUrl (Swup.modern.js:21:2892)
    at E.cacheUrl (Swup.modern.js:21:3015)
    at eval (index.modern.js:7:1125)
    at l.onreadystatechange (Swup.modern.js:21:2035)
```
**Swup config**:

```javascript
const customPayloadOption = {
    generatePageObject: ({ response }) => {
        const { html } = JSON.parse(response)
        return getDataFromHtml(html, swup.options.containers)
    }
}
const swup = new Swup({
    plugins: [
        new SwupRouteNamePlugin({
            routes: [
                { name: 'front', path: '/' },
                { name: 'projects', path: '/work-experience' },
                { name: 'about', path: '/about-me' },
                { name: 'contact', path: '/contact-me' },
            ]
        }),
        new SwupPreloadPlugin(),
        new SwupCustomPayloadPlugin(customPayloadOption)
    ],
    animateHistoryBrowsing: true,
    containers: ['#page']
});
```
Any idea what's causing this?

**Comment by daun** [comment]
The two plugins might not be compatible, I haven't used them together yet.

Does switching the order help? I.e. instantiating the custom payload plugin before the preload plugin?

**Comment by kaspost** [comment]
No, switching the order doesn't make a difference sadly

**Comment by kaspost** [comment]
@daun managed to solve it by modifying the options to this:
```javascript
const customPayloadOption = {
    generatePageObject: ({ response, responseURL }) => {
        const { html } = JSON.parse(response)
        return {  
            ...getDataFromHtml(html, swup.options.containers), 
            responseURL: responseURL || window.location.href
        }
    }
}
```
ResponseURL is required for preload plugin to work. Might be worth adding to the documentation?

**Comment by daun** [comment]
Great catch. This seems to be a problem with the cache expecting a `responseURL` property. I'll open a new issue on the main repo to address this.
